# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mmmenu 0.5.2 ruby lib

Gem::Specification.new do |s|
  s.name = "mmmenu"
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roman Snitko"]
  s.date = "2014-07-07"
  s.description = "Defines multilevel menu structures, uses custom html templates to render them."
  s.email = "roman.snitko@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/generators/mmmenu/mmmenu_generator.rb",
    "lib/generators/templates/helpers/mmmenu_helper.rb",
    "lib/generators/templates/views/mmmenu/_current_item.erb",
    "lib/generators/templates/views/mmmenu/_item.erb",
    "lib/generators/templates/views/mmmenu/_level_1.erb",
    "lib/generators/templates/views/mmmenu/_level_2.erb",
    "lib/mmmenu.rb",
    "lib/mmmenu/engine.rb",
    "lib/mmmenu/level.rb",
    "lib/mmmenu/version.rb",
    "mmmenu.gemspec",
    "spec/lib/mmmenu_level_spec.rb",
    "spec/lib/mmmenu_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/snitko/mmmenu"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Flexible menu generator for Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

